/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Outbox, OutboxInterface } from "../../contracts/Outbox";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "messageId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "fromChainId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "toChainId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "SentMessage",
    type: "event",
  },
  {
    inputs: [],
    name: "currentMessageId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060008055610281806100246000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80639f3ce55a1461003b578063f8e4e73314610050575b600080fd5b61004e6100493660046100db565b61006b565b005b61005960005481565b60405190815260200160405180910390f35b60008054908061007a836101b4565b9190505550466000547f8faadd406ba1f92f9f4c0f319ea6f827a4783f58d365a77ddfaf1796374d9699843387866040516100b894939291906101db565b60405180910390a3505050565b634e487b7160e01b600052604160045260246000fd5b6000806000606084860312156100f057600080fd5b83356001600160a01b038116811461010757600080fd5b925060208401359150604084013567ffffffffffffffff8082111561012b57600080fd5b818601915086601f83011261013f57600080fd5b813581811115610151576101516100c5565b604051601f8201601f19908116603f01168101908382118183101715610179576101796100c5565b8160405282815289602084870101111561019257600080fd5b8260208601602083013760006020848301015280955050505050509250925092565b6000600182016101d457634e487b7160e01b600052601160045260246000fd5b5060010190565b8481526000602060018060a01b038087168285015280861660408501525060806060840152835180608085015260005b818110156102275785810183015185820160a00152820161020b565b50600060a0828601015260a0601f19601f830116850101925050509594505050505056fea2646970667358221220c141aeb332bd47f4510aad3e1b19e05afc49fe9cae05030919872babcba7c44464736f6c63430008130033";

type OutboxConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OutboxConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Outbox__factory extends ContractFactory {
  constructor(...args: OutboxConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Outbox & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Outbox__factory {
    return super.connect(runner) as Outbox__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OutboxInterface {
    return new Interface(_abi) as OutboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Outbox {
    return new Contract(address, _abi, runner) as unknown as Outbox;
  }
}
